name: Test
on: [push, pull_request]

jobs:
  Basic-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Lint and Test
        run: ./gradlew ktlint test

  KotlinConsumer-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test
        working-directory: KotlinConsumer
        run: ./gradlew test

  SpringConsumer-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        working-directory: SpringConsumer
        env:
          updateSnapshots: true
        run: ./gradlew test

  AndroidConsumer-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 9
        uses: actions/setup-java@v3
        with:
          java-version: '9'
          distribution: 'adopt-openj9'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Test
        working-directory: AndroidConsumer
        run: ./gradlew test

